### ISSUE TITLE
Check if another repo is necessary

### ISSUE THREAD

**Issue by ulysseherbach** [harissa-framework/harissa#2]

**Comment by nseyler1** [comment]
Normally we don't need another repo.

We can publish from a branch see: https://cerodell.github.io/sphinx-quickstart-guide/build/html/githubpages.html and https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch.

Or we can publish it from github action: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow
