### ISSUE TITLE
Fix the `plot_network` docstring problem

### ISSUE THREAD

**Issue by ulysseherbach** [harissa-framework/harissa#31]
The problem may arise from the fact that the function has the same name as the module.
Solution: use `autosummary_filename_map`

**Comment by nseyler1** [comment]
Maybe it can be fixed with [autosummary_filename_map](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_filename_map)

**Comment by ulysseherbach** [comment]
> Maybe it can be fixed with [autosummary_filename_map](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_filename_map)

Yes but it will be better to simply reorganize the `utils` module
